# ベースイメージの指定
FROM php:7.4-apache

# Gitのインストール(Composerで必要)
# php-mysqlのインストール(データベース接続に必要)
RUN apt-get update \
    && apt-get install -y unzip git \
    && rm -rf /var/lib/apt/lists/*

# ComposerとAzure Blob Storage SDKのインストール
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer require "microsoft/azure-storage-blob"

# PHPのPDO拡張機能を有効にする
RUN docker-php-ext-install pdo_mysql

# コンテナ内の作業ディレクトリを設定
WORKDIR /var/www/html

# ホストマシンのファイルをコンテナ内にコピー
COPY . /var/www/html

# ポートの公開（80番ポートを使用）
EXPOSE 80

# コンテナが起動する際に実行されるコマンド
CMD ["php", "index.php"]
